#:schema https://mise.jdx.dev/schema/mise.json
# vim: ft=toml:
# Do not install starship here, use it externally so that zsh has it loaded as early as possible.

[settings]
experimental = true
lockfile = true
minimum_release_age = "3d"
pin = true

[settings.pipx]
uvx = true

[bootstrap.packages]
"brew:autoconf" = { os = "macos" }
"brew:bash" = { os = "macos" }
"brew:bash-completion" = { os = "macos" }
"brew:binutils" = { os = "macos" }
"brew:brotli" = { os = "macos" }
"brew:ca-certificates" = { os = "macos" }
"brew:coreutils" = { os = "macos" }
"brew:dnsmasq" = { os = "macos" }
"brew:docker" = { os = "macos" }
"brew:docker-buildx" = { os = "macos" }
"brew:docker-completion" = { os = "macos" }
"brew:docker-credential-helper" = { os = "macos" }
"brew:findutils" = { os = "macos" }
"brew:gawk" = { os = "macos" }
"brew:gcc" = { os = "macos" }
"brew:gettext" = { os = "macos" }
"brew:git" = { os = "macos" }
"brew:gmp" = { os = "macos" }
"brew:gnu-getopt" = { os = "macos" }
"brew:gnu-indent" = { os = "macos" }
"brew:gnu-sed" = { os = "macos" }
"brew:gnu-tar" = { os = "macos" }
"brew:gnu-time" = { os = "macos" }
"brew:gnu-which" = { os = "macos" }
"brew:gnupg" = { os = "macos" }
"brew:gnutls" = { os = "macos" }
"brew:gpatch" = { os = "macos" }
"brew:gpgme" = { os = "macos" }
"brew:grep" = { os = "macos" }
"brew:gzip" = { os = "macos" }
"brew:make" = { os = "macos" }
"brew:moreutils" = { os = "macos" }
"brew:ncurses" = { os = "macos" }
"brew:nettle" = { os = "macos" }
"brew:npth" = { os = "macos" }
"brew:openssl@3" = { os = "macos" }
"brew:pinentry" = { os = "macos" }
"brew:rancher-cli" = { os = "macos" }
"brew:readline" = { os = "macos" }
"brew:showkey" = { os = "macos" }
"brew:tmux" = { os = "macos" }
"brew:tree" = { os = "macos" }
"brew:unbound" = { os = "macos" }
"brew:unzip" = { os = "macos" }
"brew:wget2" = { os = "macos" }
"brew:wireguard-go" = { os = "macos" }
"brew:wireguard-tools" = { os = "macos" }
"brew:xz" = { os = "macos" }
"brew:zip" = { os = "macos" }
"brew:zsh" = { os = "macos" }
"brew:zstd" = { os = "macos" }
"brew-cask:1password" = { os = "macos" }
"brew-cask:1password-cli" = { os = "macos" }
"brew-cask:alacritty" = { os = "macos" }
"brew-cask:alfred" = { os = "macos" }
"brew-cask:alt-tab" = { os = "macos" }
"brew-cask:clocker" = { os = "macos" }
"brew-cask:firefox" = { os = "macos" }
"brew-cask:font-opendyslexic-nerd-font" = { os = "macos" }
"brew-cask:rancher" = { os = "macos" }
"brew-cask:visual-studio-code" = { os = "macos" }
"brew-cask:zed" = { os = "macos" }
"brew-cask:domt4/autoupdate" = { os = "macos" }

"apt:python3-apt" = { version = "latest" }
"apt:command-not-found" = { version = "latest" }
# pyenv dependencies
"apt:build-essential" = { version = "latest" }
"apt:libssl-dev" = { version = "latest" }
"apt:zlib1g-dev" = { version = "latest" }
"apt:libbz2-dev" = { version = "latest" }
"apt:libreadline-dev" = { version = "latest" }
"apt:libsqlite3-dev" = { version = "latest" }
"apt:curl" = { version = "latest" }
"apt:git" = { version = "latest" }
"apt:libncursesw5-dev" = { version = "latest" }
"apt:xz-utils" = { version = "latest" }
"apt:tk-dev" = { version = "latest" }
"apt:libxml2-dev" = { version = "latest" }
"apt:libxmlsec1-dev" = { version = "latest" }
"apt:libffi-dev" = { version = "latest" }
"apt:liblzma-dev" = { version = "latest" }
# ruby-build dependencies
"apt:autoconf" = { version = "latest" }
"apt:patch" = { version = "latest" }
"apt:libyaml-dev" = { version = "latest" }
"apt:libreadline6-dev" = { version = "latest" }
"apt:libgmp-dev" = { version = "latest" }
"apt:libncurses5-dev" = { version = "latest" }
"apt:libgdbm6" = { version = "latest" }
"apt:libgdbm-dev" = { version = "latest" }
"apt:libdb-dev" = { version = "latest" }
"apt:uuid-dev" = { version = "latest" }
"apt:byacc" = { version = "latest" }
"apt:file" = { version = "latest" }
"apt:zsh" = { version = "latest" }
"apt:unzip" = { version = "latest" }
[bootstrap.macos.defaults]
"com.apple.finder" = { AppleShowAllFiles = true }
[bootstrap.user]
login_shell = "/usr/bin/zsh"

[tools]

# Python package and project manager
[tools.uv]
version = "latest"

# Aqua is a tool for managing your shell environment
[tools.aqua]
version = "latest"

# cargo binstaller
[tools.cargo-binstall]
version = "latest"

# usage, required for mise completion
[tools.usager]
version = "latest"

###########################################################
######################## Languages ########################
###########################################################
[tools.python]
version = "latest"

[tools.go]
version = "latest"

[tools.ruby]
version = "latest"

[tools.rust]
version = "latest"

[tools.node]
version = "latest"

[tools.java]
version = "latest"

[tools.groovy]
version = "latest"

[tools.lua]
version = "latest"

[tools.ninja]
version = "latest"

[tools.cmake]
version = "latest"

###########################################################
########################## NodeJS #########################
###########################################################
# # js formatter
# [tools."npm:@biomejs/biome"]
# version = "latest"

###########################################################
########################## Python #########################
###########################################################

# # python linter/formatter
# [tools."ubi:astral-sh/ruff"]
# version = "latest"
# postinstall = 'ruff generate-shell-completion zsh > "~/.local/share/zsh/completions/_ruff"'

###########################################################
########################## Shell ##########################
###########################################################

# # shell formatter
# [tools."ubi:patrickvane/shfmt"]
# version = "latest"

# # shell linter
# [tools."ubi:koalaman/shellcheck"]
# version = "latest"

# # shell formatter
# [tools."pipx:beautysh"]
# version = "latest"
# uvx_args = "--with setuptools"

###########################################################
######################### Markdown ########################
###########################################################

# # markdown table of contents generator
# [tools."pipx:markdown-toc"]
# version = "latest"

# # markdown linter
# [tools."npm:markdownlint-cli2"]
# version = "latest"

# # markdown viewer
# [tools."go:github.com/charmbracelet/glow"]
# version = "latest"

# # prose linter
# [tools."ubi:errata-ai/vale"]
# version = "latest"

# # markdown formatter
# [tools."pipx:mdformat"]
# version = "latest"

# # markdown processor
# [tools."ubi:jgm/pandoc"]
# version = "latest"

###########################################################
######################### Neovim ##########################
###########################################################

# # fuzzy finder
# [tools."ubi:junegunn/fzf"]
# version = "latest"
# postinstall = 'fzf --zsh > ~/.local/share/zsh/completions/_fzf'

# # search tool
# [tools."ubi:BurntSushi/ripgrep"]
# version = "latest"
# exe = "rg"
# postinstall = 'rg -generate=complete-zsh > ~/.local/share/zsh/completions/_rg'

# # search tool
# [tools."ubi:sharkdp/fd"]
# version = "latest"

# # parser generator
# [tools."ubi:tree-sitter/tree-sitter"]
# version = "latest"
# postinstall = 'tree-sitter complete -s zsh > "~/.local/share/zsh/completions/_tree-sitter"'

# # neovim
# [tools.neovim]
# version = "latest"

# # maintained implementation of ctags
# [tools."ubi:universal-ctags/ctags-nightly-build"]
# version = "2023.12.29+e4cb2a0f9ba947d23e526888930bb1487c2cf1d8"
# exe = "ctags"

###########################################################
######################## CLI Tools ########################
###########################################################

# # notes cli
# [tools."go:github.com/naterator/notes/cmd/notes"]
# version = "latest"

# # jira cli
# [tools."github:ankitpokhrel/jira-cli"]
# version = "latest"
# postinstall = 'jira completion zsh > "~/.local/share/zsh/completions/_jira"'

# # file encryption
# [tools.age]
# version = "latest"

# # terminal video recorder
# [tools."go:github.com/charmbracelet/vhs"]
# version = "latest"

# # AI code assistant
# [tools."pipx:aider-chat"]
# version = "latest"
# exe = "aider"
# uvx_args = "--force --python python3.12"

# # 1password cli
# [tools.1password]
# version = "latest"
# postinstall = 'op completion zsh > "~/.local/share/zsh/completions/_op"'

# # backblaze cli
# [tools."pipx:b2"]
# version = "latest"
# extras = "full"

# # cloudflare tunnel
# [tools."ubi:cloudflare/cloudflared"]
# version = "latest"

# # coder cli
# [tools."ubi:coder/coder"]
# version = "latest"

# # tmux
# [tools.tmux]
# version = "latest"

# # packer
# [tools.packer]
# version = "latest"

# # jira cli
# [tools."ubi:mk-5/fjira"]
# version = "latest"
# postinstall = 'fjira completion zsh > "~/.local/share/zsh/completions/_fjira"'

# # A terminal interface for exploring and arranging tabular data.
# [tools."pipx:visidata"]
# version = "latest"

# # load/unload .env files
# [tools.direnv]
# version = "latest"

# # command line tool to correct mistakes
# [tools."pipx:thefuck"]
# version = "latest"
# uvx_args = "--with setuptools"

# # A tool for glamorous shell scripts
# [tools."ubi:charmbracelet/gum"]
# version = "latest"

# # Ultimate Plumber, a tool for writing Linux pipes
# [tools."go:github.com/akavel/up"]
# version = "latest"

# # terminal dashboard
# [tools."ubi:wtfutil/wtf"]
# version = "latest"
# exe = "wtfutil"
# rename_exe = "wtf"

# # task runner
# [tools."ubi:go-task/task"]
# version = "latest"
# postinstall = 'task --completion zsh > "~/.local/share/zsh/completions/_task"'

# # curl alternative
# [tools."ubi:ducaale/xh"]
# version = "latest"

# # disk usage analyzer
# [tools."go:github.com/dundee/gdu"]
# version = "latest"

# [tools."npm:@devcontainers/cli"]
# version = "latest"

###########################################################
########################### TOML ##########################
###########################################################

# [tools.taplo]
# version = "latest"
# postinstall = 'taplo completions zsh > "~/.local/share/zsh/completions/_taplo"'

###########################################################
########################### YAML ##########################
###########################################################

# # yaml templating tool
# [tools."ubi:carvel-dev/ytt"]
# version = "latest"
# postinstall = 'ytt completion zsh > "~/.local/share/zsh/completions/_ytt"'

# # yaml formatter
# [tools."ubi:google/yamlfmt"]
# version = "latest"

# # yaml language server
# [tools."npm:yaml-language-server"]
# version = "latest"

# # yaml processor
# [tools."ubi:mikefarah/yq"]
# version = "latest"
# postinstall = 'yq completion zsh > "~/.local/share/zsh/completions/_yq"'

# # yaml linter
# [tools."pipx:yamllint"]
# version = "latest"

###########################################################
########################### JSON ##########################
###########################################################
# # JSON viewer
# [tools."ubi:antonmedv/fx"]
# version = "latest"

# # JSON processor
# [tools."ubi:jqlang/jq"]
# version = "latest"

###########################################################
######################### Terraform #######################
###########################################################

# # hcl to json converter
# [tools.hcl2json]
# version = "latest"

# # terraform formatter
# [tools."go:github.com/bschaatsbergen/hclfmt"]
# version = "main"

# # terraform
# [tools.terraform]
# version = "latest"

# # opentofu
# [tools."ubi:opentofu/opentofu"]
# version = "latest"
# exe = "tofu"

# # cdktf
# [tools."npm:cdktf"]
# version = "latest"

# # terraform linter
# [tools."ubi:terraform-linters/tflint"]
# version = "latest"

# # terraform security scanner
# [tools."ubi:tenable/terrascan"]
# version = "latest"

# # terraform language server
# [tools.terraform-ls]
# version = "latest"

# # terraform wrapper
# [tools.terragrunt]
# version = "latest"

# # terraform docs generator
# [tools."ubi:terraform-docs/terraform-docs"]
# version = "latest"

# # terraform summary generator
# [tools."ubi:dineshba/tf-summarize"]
# version = "latest"

# # Policy enforcement for your pipelines.
# [tools."ubi:siderolabs/conform"]
# version = "latest"
# postinstall = 'conform completion zsh > "~/.local/share/zsh/completions/_conform"'

###########################################################
########################## Golang ##########################
###########################################################

# # go formatter
# [tools."go:github.com/segmentio/golines"]
# version = "latest"

# # go formatter
# [tools."go:golang.org/x/tools/cmd/goimports"]
# version = "latest"

###########################################################
########################### Rust ###########################
###########################################################

# # rust language server
# [tools.rust-analyzer]
# version = "2025-04-14"

###########################################################
########################### Git ###########################
###########################################################

# [tools."go:github.com/hickford/git-credential-oauth"]
# version = "latest"

# # git checkout branch
# [tools."go:github.com/royeo/git-checkout-branch"]
# version = "latest"
# post_install = "git config --global alias.cb checkout-branch"

# # git pre-commit hooks
# [tools."pipx:pre-commit"]
# version = "latest"

# # github cli
# [tools."ubi:cli/cli"]
# version = "latest"
# exe = "gh"

# # git UI
# [tools."ubi:jesseduffield/lazygit"]
# version = "latest"

# # bitbucket cli
# [tools."go:github.com/craftamap/bb"]
# version = "latest"

# # gitlab cli
# [tools."asdf:mise-plugins/mise-glab"]
# version = "latest"
# postinstall = 'glab completion -s zsh > "~/.local/share/zsh/completions/_glab"'

# # git diff viewer
# [tools."ubi:dandavison/delta"]
# version = "latest"

###########################################################
########################## AWS ############################
###########################################################

# # cloudformation cli
# [tools."ubi:aws-cloudformation/rain"]
# version = "latest"

# # aws cli
# [tools.awscli]
# version = "latest"

# # aws vault
# [tools."aws-vault"]
# version = "latest"

# # aws sam cli
# [tools."pipx:aws-sam-cli"]
# version = "latest"

###########################################################
########################## Google #########################
###########################################################

# # google cloud cli
# [tools.gcloud]
# version = "latest"
# postinstall = "ln -s $(mise where gcloud)/completion.zsh.inc ~/.local/share/zsh/completions/_gcloud"

###########################################################
######################## Kubernetes #######################
###########################################################

# # kustomize
# [tools.kustomize]
# version = "latest"
# postinstall = 'kustomize completion zsh > "~/.local/share/zsh/completions/_kustomize"'

# # helm
# [tools.helm]
# version = "latest"
# postinstall = 'helm completion zsh > "~/.local/share/zsh/completions/_helm"'

# # krew
# [tools.krew]
# version = "latest"

# # helm chart testing
# [tools."ubi:helm/chart-testing"]
# version = "latest"
# exe = "ct"

# # argocd
# [tools."ubi:argoproj/argo-cd"]
# version = "latest"
# postinstall = 'argocd completion zsh > "~/.local/share/zsh/completions/_argocd"'

# # k9s
# [tools."ubi:derailed/k9s"]
# version = "latest"
# postinstall = 'k9s completion zsh > "~/.local/share/zsh/completions/_k9s"'

# # argocd TUI
# [tools."ubi:darksworm/argonaut"]
# version = "latest"

# [tools.kubectl]
# version = "latest"
# postinstall = 'kubectl completion zsh > "~/.local/share/zsh/completions/_kubectl"'

###########################################################
########################## Docker #########################
###########################################################

# # docker UI
# [tools."ubi:jesseduffield/lazydocker"]
# version = "latest"

# # container scanner
# [tools."ubi:aquasecurity/trivy"]
# version = "latest"
# postinstall = 'trivy completion zsh > "~/.local/share/zsh/completions/_trivy"'

# # rancher cli
# [tools."ubi:rancher/cli"]
# version = "latest"
# exe = "rancher"

# # docker image analyzer
# [tools."go:github.com/wagoodman/dive"]
# version = "latest"
# postinstall = 'dive completion zsh > "~/.local/share/zsh/completions/_dive"'
